Add install smarty 3

diff --git a/bin/vendors b/bin/vendors
--- a/bin/vendors
+++ b/bin/vendors
@@ -1,10 +1,43 @@
-#!/bin/sh
+#!/bin/bash
 
-echo "TODO";
-exit 0
+TELCO_PATH=$(dirname $(pwd)/$(dirname $0))/;
+VENDOR_PATH=$TELCO_PATH"vendor";
 
+# Show action
+show_action () {
+    echo -e "\033[34m\n"${1}"\033[00m";
+    sleep 1;
+}
 
-sudo apt-get install subversion
+# Show error
+show_error() {
+    echo -e "\nError: "${1};
+}
+
+# Install package if isn't install
+install_package() {
+    if test "`dpkg -l | grep ${1} | wc -l`" == "0"
+    then
+        show_action "- Install ${1}";
+        apt-get install ${1}
+    fi
+}
+
+# Create directory if does'nt exists
+create_dir() {
+    if ! test -d ${1}
+    then
+        show_action "- Create dir ${1}";
+        mkdir -vp ${1}
+    fi
+}
+
+# Need subversion
+install_package subversion
+
+create_dir $VENDOR_PATH;
+cd $VENDOR_PATH;
 
 # Install smarty 3
+show_action "INSTALL SMARTY 3";
 svn checkout http://smarty-php.googlecode.com/svn/trunk/distribution smarty
